resources:
  limits:
    cpu: 2
    memory: 1024Mi
  requests:
    cpu: 0.25
    memory: 256Mi

mysql:
  name: "mysql"
  image: 
    name: docker.pkg.github.com/banzo/symfony-helm/mysql
    tag: sha-2bd3307
  port: 3306
  env:
    secret:
      MYSQL_DATABASE:
        name: "database-secret"
        key: "database"
      MYSQL_ROOT_PASSWORD:
        name: "database-secret"
        key: "password"

nginx:
  name: "nginx"
  image: 
    name: docker.pkg.github.com/banzo/symfony-helm/nginx
    tag: sha-2bd3307
  port: 80
  probes:
    liveness: /healthz
    readiness: /healthz

phpfpm:
  name: "php-fpm"
  image: 
    name: docker.pkg.github.com/banzo/symfony-helm/php-fpm
    tag: sha-2bd3307
  port: 9000
  env:
    secret:
      DATABASE_URL:
        name: "database-secret"
        key: "url"
