name: Build and Publish Docker image

# This jobs takes a list of Dockerfile (matrix), builds them and publishes them to Github Packages

on: [push]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push Mysql Docker image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: banzo/symfony-helm/mysql
          tag_with_ref: true
          tag_with_sha: true
          dockerfile: docker/mysql/Dockerfile
          path: docker/mysql
      - name: Push Nginx Docker image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: banzo/symfony-helm/nginx
          tag_with_ref: true
          tag_with_sha: true
          dockerfile: docker/nginx/Dockerfile
          #path: docker/nginx
      - name: Push php-fpm Docker image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: banzo/symfony-helm/php-fpm
          tag_with_ref: true
          tag_with_sha: true
          dockerfile: docker/php-fpm/Dockerfile
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout symfony-helm
        uses: actions/checkout@v2
      - name: Add stable repository
        run: helm repo add stable https://kubernetes-charts.storage.googleapis.com/
      - name: Update repositories
        run: helm repo update
      - name: Update dependencies of helm chart
        run: helm dep up
      - name: Get GKE Key
        env:
          GCLOUD_KEY: ${{ secrets.SA_GKE }}
        run: echo "$GCLOUD_KEY" | base64 --decode > ${HOME}/gcloud.json
      - name: Activation service account authentification
        run: gcloud auth activate-service-account --key-file=${HOME}/gcloud.json
      - name: Set the appropriate project
        env:
          GCP_PROJECT: ${{ 'bigdataatma-238514' }}
        run: gcloud config set project "$GCP_PROJECT"
      - name: Get credentials for a running cluster
        env:
          GKE_PROJECT: ${{ 'laravel' }}
          GCP_ZONE: ${{ 'europe-west1-b' }}
        run: gcloud container clusters get-credentials "$GKE_PROJECT" --zone "$GCP_ZONE"
      - name: Install Symfony application
        run: helm upgrade --install myapp .
